### PR TITLE
Update repository urls.

### PR DESCRIPTION
**Pull request by oleastre**
To make automated tools work with npmjs.com metadata, you needto updateyour package.json file to reflect the current github repository move to the regexhq organization.

Could you please update those urls and make a release, so that creating webjars for unc-path-regex can be automated ?

(see http://webjars.org for more info about that packaging format)

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@jonschlinkert should publish :)

**Comment by oleastre** [comment]
Thanks a lot.

**Comment by tunnckoCore** [comment]
Me too, it is kind a reminder that we should change such things for all the repos here, when have more time.

**Comment by jonschlinkert** [comment]
since I seem to do this to urls a lot, I finally created a linter that I'll be using (at least locally) to fix urls on projects I create. maybe I'll publish it as an "updater" once `update` is finished. 

@tunnckoCore I added you as an owner on npm

**Comment by tunnckoCore** [comment]
Okey, thanks!

**Comment by tunnckoCore** [comment]
@oleastre ready, published as `0.1.2`. And thanks again!
I'll try to do the needed updates in the org, but I want to finish `koa-better-body` and my other `koa-*` things this weekend.

**Comment by oleastre** [comment]
The webjar is now created; enabling me to use the typings project. Thanks for your support.

**Pull request merged**
